import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Dinesh Aitham</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="py-28">
        <div class="sm:flex flex-row-reverse items-center ">
            
            <img src="./dinesh.jpg" class="rounded-full h-72 w-72 mx-20"></img>
            <div class="mr-20">
              <div class="text-4xl">
                Hello, My name is Dinesh Aitham. I am 
              </div>
              <ul className='devep text-4xl'>
                <li><span>Smart Contact Developer</span></li>
                <li><span>Web3 Dapp Developer</span></li>
              </ul>
            </div>
        </div>
      </div>
    </div>
  )
}
